### PR TITLE
General improvements and modernizations

### PR DESCRIPTION
**Pull request by doronbehar**
Here are some suggestions I have for your wonderful module, the most important of which is adding a luarocks rockspec which I would like to give you the honor to upload yourself to luarocks and by that make your module more accessible.

Also, You need to choose a license and put in the rockspec file. I wasn't sure what is it from the comment in the beginning of `mpd.lua`.

EDIT:
- Fixed comment
- Here they explain how to upload a rock to luarocks.org: https://github.com/luarocks/luarocks/wiki/Creating-a-rock#submitting-a-rockspec-for-inclusion-in-the-rocks-server

### CODE REVIEW

**Comment by kaworu** [comment]
Hi @doronbehar,

Many thanks, I'm super happy if this small module is useful to others than me. I'll definitely take a close look at this PR this week-end!

Regards,
Alex.

**Comment by doronbehar** [comment]
Looking for your reply!

**Comment by kaworu** [comment]
Hi @doronbehar!

So I finally managed to get some time to test and merge your PR, thanks for your patience :)

I took the liberty to adjust the documentation, follow [semver](https://semver.org/), and adapt the rockspec file to use github directly.

I've uploaded the rockspec and I've been able to install and use the module. I would be glad if you could test it too!

Also I'm in the process of switching the license to what was a BSD-2-Clause to MIT, so that it should be more familiar for Lua users.

Regards,
Alex.

**Comment by doronbehar** [comment]
Tested and working. Cheers!

**Pull request merged**
